---
- name: Remove-node | Wait until Volumes will be detached from the node
  ansible.builtin.command: >-
    kubectl get volumeattachments -o go-template={% raw %}'{{ range .items }}{{ .spec.nodeName }}{{ "\n" }}{{ end }}'{% endraw %}
  register: nodes_with_volumes
  delegate_to: "{{ groups['masters'] | first }}"
  changed_when: false
  until: not (kube_override_hostname | default(inventory_hostname) in nodes_with_volumes.stdout_lines)
  retries: 3
  delay: "{{ drain_grace_period }}"
  when:
    - groups['masters'] | length > 0
    - not allow_ungraceful_removal
    - kube_override_hostname | default(inventory_hostname) in nodes.stdout_lines

- name: Remove-node | Delete node
  ansible.builtin.command: "kubectl delete node {{ kube_override_hostname | default(inventory_hostname) }}"
  delegate_to: "{{ groups['masters'] | first }}"
  when:
    - groups['masters'] | length > 0
    # ignore servers that are not nodes
    - inventory_hostname in groups['k8s_cluster'] and kube_override_hostname | default(inventory_hostname) in nodes.stdout_lines
  retries: "{{ delete_node_retries }}"
  # Sometimes the api-server can have a short window of indisponibility when we delete a control plane node
  changed_when: false
  delay: "{{ delete_node_delay_seconds }}"
  register: result
  until: result is not failed
