---
# tasks file for kubevip

- name: Kube-vip | Check if super-admin.conf exists
  ansible.builtin.stat:
    path: "{{ kube_config_dir }}/super-admin.conf"
  failed_when: false
  changed_when: false
  register: stat_kube_vip_super_admin

- name: Kube-vip | Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/var/lib/kubelet/config.yaml"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: kubeadm_already_run

- name: Kube-vip | Set admin.conf
  ansible.builtin.set_fact:
    kube_vip_admin_conf: admin.conf

- name: Kube-vip | Set admin.conf for first Control Plane
  ansible.builtin.set_fact:
    kube_vip_admin_conf: super-admin.conf
  when:
    - inventory_hostname == groups['masters'] | first
    - (stat_kube_vip_super_admin.stat.exists and stat_kube_vip_super_admin.stat.isreg) or (not kubeadm_already_run.stat.exists )

- name: Kube-vip | Write static pod
  ansible.builtin.template:
    src: manifests/kube-vip.manifest.j2
    dest: "{{ kube_manifest_dir }}/kube-vip.yml"
    mode: "0640"
