---
- name: CRI-O | reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: Restart crio

- name: CRI-O | reload crio
  ansible.builtin.service:
    name: crio
    state: restarted
    enabled: true
  listen: Restart crio
