---
# tasks file for post-upgrade

- name: Uncordon node
  ansible.builtin.command: "{{ kubectl }} uncordon {{ kube_override_hostname | default(inventory_hostname) }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when:
    - needs_cordoning | default(false)