---
# tasks file for node-taint

- name: Set role and inventory node taint to empty list
  ansible.builtin.set_fact:
    inventory_node_taints: []

- name: Populate inventory node taint
  ansible.builtin.set_fact:
    inventory_node_taints: "{{ inventory_node_taints + ['%s' | format(item)] }}"
  loop: "{{ node_taints | d([]) }}"
  when:
    - node_taints is defined
    - node_taints is not string
    - node_taints is not mapping
    - node_taints is iterable

- ansible.builtin.debug:  # noqa name[missing]
    var: role_node_taints
- ansible.builtin.debug:  # noqa name[missing]
    var: inventory_node_taints

- name: Set taint to node
  ansible.builtin.command: >-
    kubectl taint node {{ kube_override_hostname | default(inventory_hostname) }} {{ (role_node_taints + inventory_node_taints) | join(' ') }} --overwrite=true
  delegate_to: "{{ groups['masters'][0] }}"
  changed_when: false
  when:
    - (role_node_taints + inventory_node_taints) | length > 0
